server:
  port: 8083

spring:
  application:
    name: auth-service
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: http://user-service:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: mySuperSecretKeyThatIsAtLeast256BitsLongForHS512Algorithm12345
  expiration: 3600000
  issuer: todo-app-auth-service