server:
  port: 8083

spring:
  application:
    name: auth-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

jwt:
  secret: mySuperSecretKeyThatIsAtLeast256BitsLongForHS512Algorithm12345
  expiration: 3600000 # 1 hour in milliseconds
  issuer: todo-app-auth-service

logging:
  level:
    com.example.authservice: DEBUG
    feign: DEBUG