spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: NOTIFICATION-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka