server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: task-service
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/tasks/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: analytics-service
              uri: lb://ANALYTICS-SERVICE
              predicates:
                - Path=/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/