server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka