server:
  port: 8082

spring:
  application:
    name: TASK-SERVICE
  datasource:
    url: jdbc:h2:mem:taskdb
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  