server:
  port: 8082

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://postgres:5432/task_db
    username: task_service
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

cache:
  user-tasks-ttl: 300